name: Build Typst Documents

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v2
        with:
          typst-version: "latest" # Précise la version à télécharger

      - name: Compile CV to PDF
        run: |
          typst compile cv/cv-fr.typ cv/cv-simon-pierre-tremblay.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: cv/cv-simon-pierre-tremblay.pdf